name = "Complementary Unbound"
filename = "ComplementaryUnbound.zip"
side = "client"

[download]
url = "https://drive.google.com/uc?export=download&id=1a8XSmw6dWmXDtZjWYd1JkGoirozszOGi"
hash-format = "sha1"
hash = "fc7cc7ec3cbb8a8f16504ef3973d804200a9315d"