name = "Telkit Development Edition"
author = "Nosiphus"
version = "2026.03.01"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d49cbb310ccbec5b9948fc345a3799bcc2994da4477fd5eca79c90f69a8c05c0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = ["1.21"]
