name = "Telkit Development Edition"
author = "Nosiphus"
version = "2026.02.08"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e65da1b015c0efc057831fb1520e99cbde1bed3e65da9ffbb092229b5838e5f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = ["1.21"]
