name = "Telkit Development Edition"
author = "Nosiphus"
version = "2026.01.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a908d35032f5a2a1feeed141257552fa215629dc9127311de60b40549ab055bb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"

[options]
acceptable-game-versions = ["1.21"]
