name = "Telkit Development Edition"
author = "Nosiphus"
version = "2026.01.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16f31099d0db1b9e88decdfa04229c7f530d2c90058376c3fe321c5f3d759bb0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"

[options]
acceptable-game-versions = ["1.21"]
