name = "Telkit III"
author = "Nosiphus"
version = "2026.02.01"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d1bcfee0aa44947d44611316233c17e816f67b58a35afbf2ca98e01378b0744"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.2", "1.16.3", "1.16.4"]
