name = "Telkit V"
author = "Nosiphus"
version = "2025.11.19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54bb258dfa8289399ddfedc1868739870158fffb07368e45686d0aeee722f756"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "neoforge"]
