name = "Telkit V"
author = "Nosiphus"
version = "2026.01.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac21f39e16b61b8627674e793ab687a9cba28f49ef2a12d6abf5ce8fa75e22ed"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "neoforge"]
