name = "Telkit V"
author = "Nosiphus"
version = "2025.11.22"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3176d452efa5b5ac9313d337d326a314e640104075f1c9315e3716485d1fe3b4"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "neoforge"]
