name = "Telkit V"
author = "Nosiphus"
version = "2025.11.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fd3005c0ddc19e511776058347c812440cf206fffc099b479079aecceb166e5"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "neoforge"]
