name = "Telkit V"
author = "Nosiphus"
version = "2025.11.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5ca70c8aacb662b05dde52b010e46f1b83a69e24021ba6c7972e118f50b564c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "neoforge"]
