name = "Telkit V"
author = "Nosiphus"
version = "2026.01.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5cc3f449c1505ff598afde7068ed95c04fdec85d878e52538b7fd29157aca435"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "neoforge"]
