name = "Telkit V"
author = "Nosiphus"
version = "2025.11.28"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbdbb101beda9cd4a94539bf3113a569dd9d0bc92d8e89739e512d1748e81f7a"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "neoforge"]
