name = "Telkit V"
author = "Nosiphus"
version = "2025.11.26"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2389026c79bd242bb646560a1d79cbca6082a0351c45991a8f9c5903825897bf"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "neoforge"]
