name = "Telkit V"
author = "Nosiphus"
version = "2025.11.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebbecce90458e5e96c71461babb52cbce16233382a96450588d67eaaa90d918f"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "neoforge"]
