name = "Telkit V"
author = "Nosiphus"
version = "2026.01.30"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55431dd0082ab2c6ce9ec2127a81617d3a61719099007b4091160a18195088e5"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "neoforge"]
