name = "Telkit V"
author = "Nosiphus"
version = "2025.12.30"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97d02e05b6f9891fdad725fb4b375615fd609764e292370e215ff9d7250f7543"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "neoforge"]
