name = "Telkit V"
author = "Nosiphus"
version = "2025.12.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f2d60b1ac572f955cef061cf799a8f9049ef9e54671013de8bd2a68cd5494e2"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "neoforge"]
