name = "Telkit V"
author = "Nosiphus"
version = "2025.11.04"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6717367ceaf925498e1952e3c092bc4973e6529a8438fd67e5e13671ced4569"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "neoforge"]
