name = "Telkit V"
author = "Nosiphus"
version = "2025.12.05"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b100ede499343fd5599c7801902d7b61953648bf3a4bdb3d56c0a8f46ec46590"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "neoforge"]
