name = "Telkit V"
author = "Nosiphus"
version = "2025.11.30"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8a7e0884be06532600db77e4cb5096e1d5b5035cdc62983409b430b559e261e"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "neoforge"]
