name = "Telkit V"
author = "Nosiphus"
version = "2025.11.23"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d72216f1945d56a7dcf606c9906f9a0c9877db7eca578b025e06ea7874511962"

[versions]
forge = "47.4.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "neoforge"]
