name = "Telkit V"
author = "Nosiphus"
version = "2025.12.07"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8ab0e7d8f0c2e5f896be3d700895d1b5a62fc3a433b0ee9d36979d7e41e9332"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "neoforge"]
