name = "Telkit V"
author = "Nosiphus"
version = "2026.02.04"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d375ad04d7bf27302e99478f3eae4cc95123f7d226c785c1c7252a4415ec642"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "neoforge"]
