name = "Telkit I"
author = "Nosiphus"
version = "2025.11.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27287dd677afbaa1bd34bdd1337009d81ac3b763c91372327571ffd22521879d"

[versions]
forge = "10.13.4.1614"
liteloader = "1.7.10_04"
minecraft = "1.7.10"
