hash-format = "sha256"

[[files]]
file = "config/defaultoptions/servers.dat"
hash = "9d4e3cc05f59bdd92410062346f2374eb80261253e85c725a35c24f4bea3f87a"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "f7b7309a575abc17fe84cfd9302ba80735e63dbda489deb11484f3e2192ec5ab"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "46f31326134e5ade367611c41be800b70be39f5b1505da502a255410caabfa87"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "bbb36ff8d56ad5221b333b73b5d6d28f52088e26c919bf0d002ccc0de6ca4f6a"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "f6fdbc1d61acca0926cf565f02623080d913f43609713e637a4e5317702531a4"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "aff818a1010f31b742e7fa44eab6a8eb88bdd4ef541db0d16d5d01aa9efd0858"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "dfd739baae20fcff935031d6d93d4d85dbced6ba9d3fba645e9e17b6841b5cc6"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "dad1171c186d9ca0cdf6807066bd9097b892e7176794802a25c7acfe590ab7f7"
metafile = true

[[files]]
file = "mods/bl4cks-sit.pw.toml"
hash = "7f4c1c0c01adf9ef7930cd018af778698d21df5105de1643ef0a9a81a659f87f"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "6b408e7b83e9b769fcafe9216c6f6a528d8930c6d34f7984a9e42119b5ac7d44"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "4c1163b3f29061bfca623f570a5b96f92a7dc9ce948c88d8739cc4707cffa06c"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "618f7cc1309e9cc8d129a59a0badc820e8264a5f0b3b47def75c0bfcc1668565"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "2028a52d976cb033f421516743febd52c4da21083b634fe27fa2c37112dbca13"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "b6929c7b6eb47dc00d3ffa76e5110e9b1c016c87fbd0d030d0909b7103c39573"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "d87dfb54d1b3271fc9aecfa467b9723b525095bf8c11c74659d6a546fb2f7c31"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "bca24618ea734d8b643a5d6b9697f8234880de18e199b49ea84c646973fd6556"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "7632d5c35f90b5dcd95ad649a9d95c5d79d3235e6abb655980d0c20e41e00197"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "c89bd844bf404ded89eb0fea4767a3f8b7b40662c5a386d87f0c5608ac545ed6"
metafile = true

[[files]]
file = "mods/dynamic-torches.pw.toml"
hash = "f5f4bd704da77dc6472ded8ef79de678d9a5b8501f8920e4069c482cab0547a1"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "578f4dcea55c71b9565d7d4079d9c02c4bbf860e3c7381d16bdfa793b77c33ba"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "8aa515b4d828d1b8f16b22c3390a29d515f2a3d7dd47e39a1256408e031e5729"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "16ac2dd84663e0bd2321af3d4a4d027a15bcec2e4bddd77b2469ccc5545759d6"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
hash = "ba0f44ddf5b1203bf1844251c4176459e692c9c70d7e652fa373dca2eb54e3b4"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "4385a242de62d01f91894aa2b011bb53cfdcfbdd4d950def81ec78aba7be66a3"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "ca16eaf9e6d3694b518371d1b4f2ba2140b056d228a1b497b0c0401f88555526"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "c89ff9e2017907eee684602c90257b0a69b65c605e45e819bf1ebd1764a919e4"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "6488e760f7ba14eaa71991889a0f4228fea5ff51e23265ba64512ca3cbf83a50"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "ec6d958d8ec0dbac31afcaa4414aa7f25ad8f97af6168a8d116653bd8f8e5925"
metafile = true

[[files]]
file = "mods/kleeslabs.pw.toml"
hash = "b09196a8a2807ec8078a83f3a72e9b52487000abd5604248be05af63045cc86a"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "a66e2bd6deccaab80afcfebec417d29fd19597c6231eb475112717848a5a6f94"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "e2a0b29673d3a5abac04b62156352a337b088402b0dc216550bc8af6d16a683a"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "249d8e7300c832e8ecd0b155ff38194f43463af0de0d05d3398a1a43b76d64c9"
metafile = true

[[files]]
file = "mods/moderner-beta.pw.toml"
hash = "f64f30dfcd7fbd8e0f3fddd7b82f09aa0ce458d2c5de6d97c3f674295e810c0f"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "5daad88f3e1d1a77eecf31c9a25acd6fe368d0c69c4548c6f439172605a90769"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "bda58f7e545592a653cbff9f043449644e2f17006f73a5e2529c1b4ab5dbe796"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "18d4af5a27d8bbcb2f938120c48d7f02d18cd67f7cfd517276ed23098e67da87"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "d04c5693d1cb6a5e28ab0b9973d9e6481f069dc072005a471a05ff457579140b"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "4079cb293787da07e4d2dc7fdabba004449e415bccc06c4d4ddbfab3b34c59db"
metafile = true

[[files]]
file = "mods/no-chat-restrictions.pw.toml"
hash = "4290cec0785c6140047148e7c9e600c7119cdbb622896bcdd19bbe2e0a4fda9f"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "3aac9c45822ac00fdb0f2b834e0020af0c78a559681540e25af8c67bbca3cc8d"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "41e05abbe91773742271315482ec9dfcb319531d8ac7fe0ae47117b6e0c9ed60"
metafile = true

[[files]]
file = "mods/refurbished-furniture.pw.toml"
hash = "89fdb4c4438d354f138ff6566a89768ee8edd01de2ab60f6229f3a7a5f0435c9"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "07e21938740b4d8e8efaa8d3bc16f7655e437534651ed48582fbb9e0dcab9540"
metafile = true

[[files]]
file = "mods/snow-under-trees-remastered.pw.toml"
hash = "a320c10e193760758c587eee211225564d29d06c4708a1f5e099a2c9cdb375e9"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "678a47daf8ac825c971edbf3f982ce42d3f8dfea0089ac454c6c03c94e2e9551"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "14bc514162397cec40090ac45aa100cf325350b78924a54ead79c3062ee9b9b5"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "5c5b130d63f54d978324013f22dc1f91265808ae4176c2e009eea82efd69500e"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "8b51309b0dbddf8fa603bfece75ea97ac674a396e8f06cd319d90e32f195e4d6"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "19350f81a046841ab79096759aadb58560cb360c7f6f24d2388a3e614edac288"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "bd23e870f41ca2ecb25550c4ce4ec118b0bbd2f3bde2fedb0b14ebb544a6846c"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "4c6bae43c926cc595073b266c7558d0a20ef4e81ae8f5eda333ad368da73d977"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
hash = "e82c6b10063edcb2d01e342695c10d503ab9a382d2d04cbffdbcc07104f2b070"
metafile = true
