hash-format = "sha256"

[[files]]
file = "config/defaultoptions/servers.dat"
hash = "9d4e3cc05f59bdd92410062346f2374eb80261253e85c725a35c24f4bea3f87a"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "464e689ff88c75ed3edb3a63b13dbf0dcd993079317613408102def8264e0a26"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "5606e59f9cc08de679bff2234eea343f78ab91b5832fabfa6af9b0d807be7968"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "059850e03a67a806fbe0018a5765ff60f11014221a893af36bcc24779951bc55"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "240ecedc7fb969d0206e9de97a62125e6efb0bc388fab3d83c4d2774f610c353"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "6204ffe9191fe43e90ca749735ff7c3014555045417da1715e559acacb2b4126"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "ce06a9ea5b06d4f60e0ea1f94109768948dcbb8cd3a9f5305445ea6b6683798d"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "d1b771355272dd080b00c13b035a972a8fec5234033c0166252db90b8bfee0ac"
metafile = true

[[files]]
file = "mods/bl4cks-sit.pw.toml"
hash = "3c012bb631de8717afebc7fddc22432b24d5f855cb73ef7a99d3bca1d7de6db9"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "b2103de7f3d13a7b7868890afd358e51f93bea4914e226fc0fbe53bdb84ff7e8"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "8ca94ad0380d762523be070b1648ad156807346723137f71ee49115c9e922703"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "bfe357b842a6e6477841cb1e39912916ee1a9e8a4061d7dae5064e0f0c4c9427"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "5a10992f3a471021e3a1c63727b7437dc04190efd5f3be1531bfb9f0b08230e9"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "8696d727f65e453f0942ac900c7b855274feff7561de75a198840cbd12597e2b"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "6582c187dbb80d76cc5a6681e77dd3e29ac983e486fda8876c89a7866f68397a"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "3871ad3f838dfd60c6406dcb225eb8d86d1800666ac2260fd5d0d16feb39d8a4"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "5037e915708fc7eabe7d598d3b0c111fdcfacee3995a6b58d2ad7837642c0bef"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "f6cd74197dcfcc06faf2c75aafabf384296e841e5456de54550264fe86229dc5"
metafile = true

[[files]]
file = "mods/dynamic-torches.pw.toml"
hash = "f5f4bd704da77dc6472ded8ef79de678d9a5b8501f8920e4069c482cab0547a1"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "7286129334ad60fb0e9d5f99ff38fc4fa3073e03c0f7051f5917adc3abea9efc"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "fa8be992c1e3efbd030ef6a84409b766a936deb3fc3d06b657f8e468745044f0"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "9fcda89124c70460c43252a535a31af0446f939cd5812ad0c1dd0a0514bcd855"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
hash = "f20c9ef3e472bf26e24c9f67cbcf16b3387c39fdbcc752efe74ee281349fad3b"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "4eb0060a2288f8f0f97e87eec65493e3e21f1f81ce6a6343e54ed296aadee957"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "ac0b84ad1e0633c17eccfc77c6a9b08b3d9efe5dd8e65f0f831df18779640c64"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "0d3fc40cfb3115e5f7df097d74f82806800ed051909b808fb74e28b89cb1c235"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "610fa4759525292a079fb14ce8805a36f357e0b4b2e1dc02582395d641f12421"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "cc5fee6801859738006fe32cf8a5da64a8b4c97877bdba3f422a64edcb973b7e"
metafile = true

[[files]]
file = "mods/kleeslabs.pw.toml"
hash = "eeba0a07e0790cf730d473de08d3ee112383e151383cc3186cdd4dd90b5526f5"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "a66e2bd6deccaab80afcfebec417d29fd19597c6231eb475112717848a5a6f94"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "5787b1deb7975af608901df0bf16b1e5de2452c98808f6a205c35aaa83e9f56a"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "9df913674f1ca1b37098587387f62e69df86f3abe50d9c506cf6cb518a6e1228"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "0a4f308e5c80c7eca2c1ef1117fd23731523b0e4b7c93bf298165af27af93a60"
metafile = true

[[files]]
file = "mods/moderner-beta.pw.toml"
hash = "96efb4fb25d6a706c02b2b43c010bfe95709caf311a10a37052e5b0220e7de68"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "9cb7b03b45eb9eede9748fd6dfb4de9396378ce7883da6d0da657675c7aa060d"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "d5bca4586a875c67e818b85a0b196e65aaa860ad8471c278ad85b792e7a88362"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "fb19d06661ac56150fc7fb7c83784cc3d9c0d794d6ab10ac0eb9b23ae9b330d8"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "269561f7cdadb6dffb36d9cfc3374d62027c609a72bca44d2746a93a0958154d"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "496e3a365c23a9c7b1547812f86ecd2bb6364fa7f35f68547ec2d5fe9d6fe09c"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "3aac9c45822ac00fdb0f2b834e0020af0c78a559681540e25af8c67bbca3cc8d"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "8ced9b74b91b485f78d0b56fa54bc352dd71db8e52a5e234cf6872cdf9e71aad"
metafile = true

[[files]]
file = "mods/refurbished-furniture.pw.toml"
hash = "c50770300b6a02a0dec46e4915cd11167030d5a3c2b41bfe3dff6ceb7c87a14a"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "590bd71a45f826c5e1ecda3adf133b19731ab9dc74d6582d259562aed70f2db2"
metafile = true

[[files]]
file = "mods/snow-under-trees-remastered.pw.toml"
hash = "eda64ca339141bcfc4964100a269884f90b57fefab506ca39b1d2ba86dc3e561"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "5e28a5bc87a799a03a72e641c1118b7d9ba955dceb70e2427fe0c2b15ed5186e"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "42aeb38d1205728adbe988625f969ddb6cd8f7ee7acdad50799399079d89be0d"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "fbb68e5991ad23a75679bc7deae303166393ec3108e40d133054a4cc8914e5fd"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "902baad9c216662293ddd939cf02941ba97910f7c3a6d9648a07c4d378710075"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "ffd2baef6c282d9a2e68adacbf1091e4dd0e85ca68cfe9ea869ad2f07445cb81"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "e379bf24b717a74d0f9aa4dc463991fda89fc9f7316b4bbc5dd75b411676b3c1"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "39b4cccb2535a746e6597c84eaaa3052c0c20f2dd0704dfe853ffa5853dfb3d6"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
hash = "0c057b2985906496a3ba624bd4e777469688767d934acbf7f91a7e18addc072c"
metafile = true
