name = "Nosiphus Vanilla+"
author = "Nosiphus"
version = "2025.11.28"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64778058789a2331acaaf8fe98b1198901806ffe5f29a615b976765c7ea268fa"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.5", "1.21.6", "1.21.7", "1.21.8", "1.21.9"]
