name = "Nosiphus Vanilla+"
author = "Nosiphus"
version = "2025.11.23"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15757536e5a7db92cf26a09d22071810e9d0f7e7cbe5c35299cfe7731814b575"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.5", "1.21.6", "1.21.7", "1.21.8", "1.21.9"]
