name = "Nosiphus Vanilla+"
author = "Nosiphus"
version = "2025.11.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43595cb0f9a801a5fa5b950068e247f1ffd61fa2e2a36b2e208d39333f6f9dad"

[versions]
fabric = "0.18.0"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.5", "1.21.6", "1.21.7", "1.21.8", "1.21.9"]
