name = "Telkit IV"
author = "Nosiphus"
version = "2025.12.01"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18b027e1bdbd2ef27d20edc49523d7f2b37fad66c3f8394e7c006777a996e58a"

[versions]
forge = "43.5.1"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.1", "1.19"]
