name = "Telkit IV"
author = "Nosiphus"
version = "2026.01.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "910d10123ccacf39abb8dba3b6031bc8dfaf466088981429066bae06d464701a"

[versions]
forge = "43.5.2"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.1", "1.19"]
