name = "Telkit IV"
author = "Nosiphus"
version = "2025.11.28"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0eff1c451902d248d897b51654e8bc658d3e953bcd23597ee050887fbe19403c"

[versions]
forge = "43.5.1"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.1", "1.19"]
