name = "Telkit IV"
author = "Nosiphus"
version = "2025.11.02"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2d1da7b1fad0f5a48cc5c720cdb64d4b19d844b27a39e96cca011677fb7325d"

[versions]
forge = "43.5.1"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.1", "1.19"]
