name = "Telkit IV"
author = "Nosiphus"
version = "2025.11.22"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e10729638775a4990907d9cebe440a09c94f58d619d90463caccc9e6d137df06"

[versions]
forge = "43.5.1"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.1", "1.19"]
