name = "Telkit II"
author = "Nosiphus"
version = "2025.11.28"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd6bb8febbda219220168b146b8c9778af9710493f396fe1762e74667c9964c1"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"

[options]
acceptable-game-versions = ["1.12", "1.12.1"]
