name = "Telkit II"
author = "Nosiphus"
version = "2026.02.01"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cac0c664a3867c39246d68a892554363514add1d57a736ec01c47b1ffe8e5f06"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"

[options]
acceptable-game-versions = ["1.12", "1.12.1"]
