name = "Telkit II"
author = "Nosiphus"
version = "2026.02.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98cf818c7b65dc7dd21045d45b35904a08bf0fdd40c6b61de413410a199a3a10"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"

[options]
acceptable-game-versions = ["1.12", "1.12.1"]
