name = "Telkit II"
author = "Nosiphus"
version = "2026.01.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c7afd823318b770bb469df0e6cff4fd85041ac5a2d271ab107d15d1350f156e"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"

[options]
acceptable-game-versions = ["1.12", "1.12.1"]
