hash-format = "sha256"

[[files]]
file = "Flan/manus-civil-package.toml"
hash = "650758903a9a952e879f2362e0a4c2559bc1a574fd48c986ca205027c974af3f"
metafile = true

[[files]]
file = "Flan/manus-dayz-package.toml"
hash = "0387c9a9a77e531fd3bf148ef469f5fd3493025b3403e1cb1208d922cc7b9a40"
metafile = true

[[files]]
file = "Flan/manus-ships-package.toml"
hash = "5cb8a5914e08c4d9db5cc5d1f45674cf5f794bad0850ab4b2b5a171904bcb39b"
metafile = true

[[files]]
file = "Flan/manus-warhammer-package.toml"
hash = "e9696fb8a16898906f14b38f24a263b7a19780992ec7a51ac3c79eb1c47d2b8a"
metafile = true

[[files]]
file = "Flan/manus-wwii-package.toml"
hash = "7ac4720f552faff3ce555be6b60a166c18eaf3224edf81dad2e3b151a1060474"
metafile = true

[[files]]
file = "Flan/mecha-parts-content-pack.toml"
hash = "bb566542989b9e40faae90137f4ba8bce3fd1f156ca57d29037c7e868d5915b2"
metafile = true

[[files]]
file = "Flan/minecraft-smp-parts-package.toml"
hash = "d0321ad73ab30a711858cd5597d25ed010b19cba5e84b1ecdab356c44ee2adbc"
metafile = true

[[files]]
file = "Flan/modern-warfare-content-pack.toml"
hash = "3e9dd9b4d492407c9fdfa72a3ac3eaf5e163f1f908b9032aea7c50ef8a898181"
metafile = true

[[files]]
file = "Flan/nerf-content-pack.toml"
hash = "2a882c16d7721152213e87b9ed6b2875881a98d56f2848dbe792a20d0c0987a6"
metafile = true

[[files]]
file = "Flan/simple-parts-content-pack.toml"
hash = "eff4a77b226a952c809a7f1dfab790ed559eb7b4f8c1752abcda4f36b146f243"
metafile = true

[[files]]
file = "Flan/titan-content-pack.toml"
hash = "a6839c47b1786a33b088c2e90f52e22f7c30fedf5c04e168a8d023d032ef5f0b"
metafile = true

[[files]]
file = "Flan/world-war-ii-content-pack.toml"
hash = "ed677ab5a6e197d2e5663236cf76fe3035aee914e910be9d8de4ce7f0b4c0452"
metafile = true

[[files]]
file = "Flan/ye-olde-content-pack.toml"
hash = "5829b5a6bc8435677fb248a58f12f76ac2d5273c5bc045ab2b602d31e4a4403c"
metafile = true

[[files]]
file = "config/WTP.cfg"
hash = "0749163dde3083807716b39a30498aaafbff84d83bb2254295d0c84eafd92612"

[[files]]
file = "config/bspkrsCore.cfg"
hash = "47fa41c2dcf7ea902213b14cbec86592e9538315836d47eedb7502967048f693"

[[files]]
file = "config/cfm.cfg"
hash = "9f9934508bd962c014b8637b4728c72738fe3c240f360fa0829cf55f9ae28998"

[[files]]
file = "mods/1.7.10/bspkrscore.pw.toml"
hash = "4f817806167f7b13e933b98928a698b9db0a8337af286d03c98ea13a8662a7b8"
metafile = true

[[files]]
file = "mods/ai-improvements.pw.toml"
hash = "06250d70894edf1c103aa82fd034fd8718d8f409c1db2b2de1e1c614b266e2eb"
metafile = true

[[files]]
file = "mods/archaicfix.pw.toml"
hash = "ee48491619ea973bf167c7cdc3b2f5b6f59ab4d0aa50f9cb572886b7aa8f352b"
metafile = true

[[files]]
file = "mods/balkons-weaponmod-legacy.pw.toml"
hash = "9c62aa1335670bb1e578240be37828d9f29577cc688b3902b5507a79ec36d515"
metafile = true

[[files]]
file = "mods/codechickencore-unofficial.pw.toml"
hash = "35f9d9e6bf00ade5e2e39a47d8a3cc9e47087a184c016fcac9c973f106839b4c"
metafile = true

[[files]]
file = "mods/coretweaks.toml"
hash = "3be2c24249f487ea304906e0f86f912be4a66b0cbb400709b4a0155284ed21f2"
metafile = true

[[files]]
file = "mods/daflight.toml"
hash = "79f42fa3f49e24708c98045a82f2ad6f1ed82b8103dcdf61cda88d6b928ea171"
metafile = true

[[files]]
file = "mods/endercore.pw.toml"
hash = "caa3d0023b08b8b7152c4bb76614d585651cd05aae263df31e4c672783f59363"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "47d71b304d5358da4e15bb10ef4ffa0c095280d86e040f93b1b6621ccfa9f4b5"
metafile = true

[[files]]
file = "mods/flans-mod.toml"
hash = "3ccb69899dcdd682add186f6dee0871b3966a26db10919906f82ca594be55eb9"
metafile = true

[[files]]
file = "mods/foamfix.pw.toml"
hash = "9094e82bb9ceb62536b856e42fe2041debfff3ee3ecd591b004e8119f908a7d4"
metafile = true

[[files]]
file = "mods/fps-reducer.pw.toml"
hash = "5e4119133b96b39d3daa4fb5a5197e27bc5b092ba61824b8fff5761556122c2d"
metafile = true

[[files]]
file = "mods/fullscreen-windowed-borderless-for-minecraft.pw.toml"
hash = "2e61fd567c10e346687f6a2a337723bf5d17fb4059fdb82ec50ab6dc7508ab05"
metafile = true

[[files]]
file = "mods/iron-chest-unofficial.pw.toml"
hash = "a1fde7888ad1bb85e6bfb1e5fdef002dc5e04c10af320698440bf818462bdca3"
metafile = true

[[files]]
file = "mods/lumy-skin-patch.pw.toml"
hash = "cae456bcee6de42f573895096ada1aa74ebb33930ee67b545b79a128be2cc538"
metafile = true

[[files]]
file = "mods/mrcrayfish-furniture-mod.toml"
hash = "5dcf5051f83afe7cb33bf2854b37cd9c1d9735959cebe0cfeb697c604d221c5d"
metafile = true

[[files]]
file = "mods/myceliumlib.pw.toml"
hash = "9a4b0ba9a7457952f44516c07dcdd9a3d280a6734ff651ac36f91de55d15d33c"
metafile = true

[[files]]
file = "mods/nd1710.pw.toml"
hash = "6dd45e8549a288aa42bd00bc9ccb30904d086b25fbb0fddc62a3c0deb268cfba"
metafile = true

[[files]]
file = "mods/nei-addons.pw.toml"
hash = "1f1b9809a0e8a144ea2428a67144256fbc9816f4a29a1878b4720558952ad391"
metafile = true

[[files]]
file = "mods/nei-integration.toml"
hash = "942a755257b33a08734632746be643736e56127f4c77144cd7b39431c0af207b"
metafile = true

[[files]]
file = "mods/notenoughitems-unofficial.pw.toml"
hash = "2b03ad7e10ca192156332f8754f80842c0bd039c7c086a2120277b172add0088"
metafile = true

[[files]]
file = "mods/optifine.toml"
hash = "c8a1be3cb93d2ed168501196a33011893c96b64e0b64baefe24414cfbf444266"
metafile = true

[[files]]
file = "mods/serializationisbad.pw.toml"
hash = "64fbb565e6f441cacd9007431810a2798061b637741099d01adc92b784dc51ad"
metafile = true

[[files]]
file = "mods/treecapitator.pw.toml"
hash = "548becfe83371f2af2a3eb0918ac4f8a19e82a3f16c316ed11382b6caa807440"
metafile = true

[[files]]
file = "mods/unimixins.pw.toml"
hash = "d028269df9550f9157c5196c85e11c3744671c3c7ea4ce5ad501c4618482a3c8"
metafile = true

[[files]]
file = "mods/voxelmap.pw.toml"
hash = "a7197567f4eb621b13aef16c47578d6ca34f1b6a4b48d27ca791553c583f49a0"
metafile = true

[[files]]
file = "mods/waila-plugins.pw.toml"
hash = "eea4af056e9818a21b94eb400def3c0987396806bffc46e8aaedc610b2b846db"
metafile = true

[[files]]
file = "mods/waila.pw.toml"
hash = "1ce389a8d9488dd7d37490c1498d10412b7430b18cc0faa28f47afc9cf896b57"
metafile = true

[[files]]
file = "mods/wawla.pw.toml"
hash = "e25d0fabd7c365e65c74c983621615f959d3ace9b53bdcad2e638b0cc7a6d51a"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "cc939b143f877079631c0101b8395f5e29bf7e2194897a136088fc92bd8fa704"
metafile = true

[[files]]
file = "mods/wtp-whats-this-pack.pw.toml"
hash = "d3ff2ee62711f893e6170d6be80906dc0334f984db3c7409475fe36694a946ae"
metafile = true
