name = "Maguire's Apocalypse"
author = "Nosiphus"
version = "2026.02.01"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1fa3e2e9c69bac5925339c51521cbf3bd8753c44814bbe5b6f44e0cedc470c9"

[versions]
forge = "10.13.4.1614"
liteloader = "1.7.10_04"
minecraft = "1.7.10"
